### ISSUE TITLE
Initial implementation known issues 

### ISSUE THREAD

**Issue by roll** [openspending/os-conductor#2]
- [x] coveralls dosn't work with Shippable (use coveralls command locally to send a report). Error: `Couldn't find a repository matching this job.`
- [x] move from Shippable to Travis (enhancement)?
- [ ] Authz use stringifyed json data as payload for request and response. Use JSON content type?

**Comment by pwalsh** [comment]
@akariv while you are working on conductor, maybe you want to check the last issue that @roll left unchecked here, and decide on if you want to leave it as is, or change it. At least, we should be very consistent in our request and response payloads across all services and happy for you to take the call / make changes as necessary.

**Comment by pwalsh** [comment]
https://github.com/openspending/openspending/issues/887
