### ISSUE TITLE
Deploy to new location

### ISSUE THREAD

**Issue by pwalsh** [openspending/os-conductor#3]
@roll `os-authz` on Heroku. You have perms.

**Comment by roll** [comment]
@pwalsh done. to work with OK AWS environment variables have to be changed - https://dashboard.heroku.com/apps/os-authz/settings (OPENSPENDING_*)

**Comment by pwalsh** [comment]
Thanks @roll. Will do.

**Comment by pwalsh** [comment]
DONE.
