### ISSUE TITLE
Code Style and tooling

### ISSUE THREAD

**Issue by akariv** [openspending/os-conductor#7]
- [ ] Make sure code is Py2/3 compatible
 - [ ] Improve style and readability, simplify when possible
 - [ ] Update to use our current recommended set of tools

**Comment by akariv** [comment]
For Python 2/3 code with we are writing here, I strongly recommend that we always start files like:

```
# -*- coding: utf-8 -*-
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals
```

Which prevents many potential surprises, and provides API consistency.

**Comment by akariv** [comment]
- [ ] Change views to be function based whenever possible

**Comment by pwalsh** [comment]
https://github.com/openspending/openspending/issues/887
